Dashboard-Ecommerce/Controllers/BrandController.cs
using DAL.Models;
using Dashboard_Ecommerce.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.AspNetCore.SignalR.Protocol;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using X.PagedList;

namespace Dashboard_Ecommerce.Controllers
{
    [Authorize]
    public class BrandController : Controller
    {
        private readonly MoDbContext _context;
        private readonly IToastNotification _toastNotification;
        private readonly IWebHostEnvironment _hosting;


        public BrandController(MoDbContext context, IToastNotification toastNotification, IWebHostEnvironment hosting)
        {
            _context = context;
            _toastNotification = toastNotification;
            _hosting = hosting;
        }

        [HttpGet]
        public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 50)
        {
            var Brands = await _context.SrBrands.OrderByDescending(b=>b.BrandId).ToPagedListAsync(pageIndex,pageSize);
            return View(Brands);
        }

        [HttpPost]
        public async Task<IActionResult> IndexFilter(int pageIndex = 1, int pageSize = 50,string DescA = "")
        {
            IPagedList<SrBrand> Brands = await _context.SrBrands.ToPagedListAsync(pageIndex, pageSize);

            if(DescA != string.Empty)
            {
                Brands = await _context.SrBrands.Where(b=>b.DescA == DescA).ToPagedListAsync(pageIndex, pageSize);
                ViewBag.SelectedDescA = DescA; 

            }

            return View("Index", Brands);
        }

        public IActionResult Create()
        {
            var AddBrand = new BrandDto();
            return View("BrandForm", AddBrand);
        }

        [HttpPost]
        public IActionResult Create(BrandDto dto)
        {
            if (!ModelState.IsValid)
            {
                return View("BrandForm", dto);
            }

            string FileName = string.Empty;
            bool BrandHaveImage = false;

            if(dto.ImageFile != null)
            {
                string uploads = Path.Combine(_hosting.WebRootPath, "uploads");
                FileName = Guid.NewGuid().ToString() + dto.ImageFile.FileName;
                string FullPath = Path.Combine(uploads, FileName);
                dto.ImageFile.CopyTo(new FileStream(FullPath, FileMode.Create));
                BrandHaveImage = true;
            }


            var brand = new SrBrand()
            {
                DescA = dto.DescA,
                DescE = dto.DescE,
                ImagePath = FileName,
                WithImage = BrandHaveImage
            };

            _context.SrBrands.Add(brand);
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Brand Created Successfully");
             
            return RedirectToAction("Index");

        }

        public async Task<IActionResult> Edit(int? BrandId)
        {
            if(BrandId == null) 
                return BadRequest();

            var brand = await _context.SrBrands.FindAsync(BrandId);

            if (brand == null)
                return NotFound();

            var BrandEdit = new BrandDto()
            {
                BrandId = brand.BrandId,
                DescA = brand.DescA,
                DescE = brand.DescE,
                ImagePath = brand.ImagePath
            };


            return View("BrandForm", BrandEdit);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(BrandDto dto)
        {
            if (!ModelState.IsValid)
                return View("BrandForm", dto);

            var brand = await _context.SrBrands.FindAsync(dto.BrandId);

            if (brand == null)
                return NotFound();

            string FileName = string.Empty;
            bool BrandHaveImage = false;



            if (dto.ImageFile != null)
            {
                string uploads = Path.Combine(_hosting.WebRootPath, "uploads");
                FileName = Guid.NewGuid().ToString() + dto.ImageFile.FileName;
                string FullPath = Path.Combine(uploads, FileName);

                dto.ImageFile.CopyTo(new FileStream(FullPath, FileMode.Create));
                BrandHaveImage = true;
            }


            brand.DescA = dto.DescA;
            brand.DescE = dto.DescE;
            if (!string.IsNullOrEmpty(FileName))
            {
                brand.ImagePath = FileName;
                brand.WithImage = BrandHaveImage;

            }


            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Brand Updated Successfully");

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();
            var brand = await _context.SrBrands.FindAsync(id);
            if (brand == null)
                return NotFound();

            _context.SrBrands.Remove(brand);
            _context.SaveChanges();
            return Ok();
        }
    }
}

Dashboard-Ecommerce/Controllers/CategoryController.cs
using DAL.Models;
using Dashboard_Ecommerce.Dtos;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;
using System.Security.Cryptography;
using System.Threading.Tasks;
using X.PagedList;

namespace Dashboard_Ecommerce.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly MoDbContext _context;
        private readonly IToastNotification _toastNotification;
        private readonly IWebHostEnvironment _hosting;


        public CategoryController(MoDbContext context,IToastNotification toastNotification,IWebHostEnvironment hosting)
        {
            _context = context;
            _toastNotification = toastNotification;
            _hosting = hosting;
        }

        public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 50)
        {
            var cat = await _context.MsItemCategories.OrderByDescending(c=>c.ItemCategoryId).ToPagedListAsync(pageIndex, pageSize);
            
            return View(cat);
        }
        [HttpPost]
        public async Task<IActionResult> IndexFilter(int pageIndex = 1, int pageSize = 50,string ItemCatDescA = "")
        {
            var cat = await _context.MsItemCategories.OrderByDescending(c => c.ItemCategoryId).ToPagedListAsync(pageIndex, pageSize);

            if(ItemCatDescA != string.Empty)
            {
                cat = await _context.MsItemCategories.OrderByDescending(c => c.ItemCategoryId).Where(c=>c.ItemCatDescA == ItemCatDescA).ToPagedListAsync(pageIndex, pageSize);
                ViewBag.SelectedItemCatDescA = ItemCatDescA;

            }

            return View("Index", cat);
        }

        public IActionResult Create()
        {
            var cat = new CategoryDto();
            return View("CategoryForm",cat);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CategoryDto dto)
        {
            if (!ModelState.IsValid)
                return View("CategoryForm",dto);

            string FileName = string.Empty;
            bool CategoryHaveImage = false;

            if (dto.ImageFile != null)
            {
                string uploads = Path.Combine(_hosting.WebRootPath, "uploads");
                FileName = Guid.NewGuid().ToString() + dto.ImageFile.FileName;
                string FullPath = Path.Combine(uploads, FileName);
                dto.ImageFile.CopyTo(new FileStream(FullPath, FileMode.Create));
                CategoryHaveImage = true;
            }

            var catTable = new MsItemCategory()
            {
                ItemCatDescA = dto.ItemCatDescA,
                ItemCatDescE = dto.ItemCatDescE,
                ImagePath = FileName,
                ImageDescription = dto.ImageDescription,
                ImageDescriptionEn = dto.ImageDescriptionEn,
                WithImage = CategoryHaveImage
            };

            await _context.MsItemCategories.AddAsync(catTable);
            catTable.ItemCatCode = (catTable.ItemCategoryId).ToString();
            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Category Created Successfully");


            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int? ItemCategoryId)
        {
            if (ItemCategoryId == null)
                return BadRequest();

            var cat = await _context.MsItemCategories.FindAsync(ItemCategoryId);

            if (cat == null)
                return NotFound();

            var catDto = new CategoryDto()
            {
                ItemCategoryId = cat.ItemCategoryId,
                ItemCatDescA = cat.ItemCatDescA,
                ItemCatDescE = cat.ItemCatDescE,
                ImageDescription = cat.ImageDescription,
                ImageDescriptionEn = cat.ImageDescriptionEn,
                ImagePath = cat.ImagePath 
            };

            return View("CategoryForm", catDto);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CategoryDto dto)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var catFromTable = await _context.MsItemCategories.FindAsync(dto.ItemCategoryId);

            if (catFromTable == null)
                return NotFound();
            bool CategoryHaveImage = false;

            string FileName = string.Empty;

            if (dto.ImageFile != null)
            {
                string uploads = Path.Combine(_hosting.WebRootPath, "uploads");
                FileName = Guid.NewGuid().ToString() + dto.ImageFile.FileName;
                string FullPath = Path.Combine(uploads, FileName);
                string OldFileName = catFromTable.ImagePath;
                string FullOldPath = string.Empty;
               
                dto.ImageFile.CopyTo(new FileStream(FullPath, FileMode.Create));
                CategoryHaveImage = true;

            }


            catFromTable.ItemCatDescA = dto.ItemCatDescA;
            catFromTable.ItemCatDescE = dto.ItemCatDescE;
            if (!string.IsNullOrEmpty(FileName))
            {
                catFromTable.ImagePath = FileName;
                catFromTable.WithImage = CategoryHaveImage;

            }

            catFromTable.ImageDescription = dto.ImageDescription;
            catFromTable.ImageDescriptionEn = dto.ImageDescriptionEn;

            _context.SaveChanges();

            _toastNotification.AddSuccessToastMessage("Category Updated Successfully");

            return RedirectToAction(nameof(Index));
            
                
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return BadRequest();
            var cat = await _context.MsItemCategories.FindAsync(id);
            if (cat == null)
                return NotFound();


            _context.MsItemCategories.Remove(cat);
            _context.SaveChanges();

            return Ok();
        }
    }
}

Dashboard-Ecommerce/Controllers/CompanyController.cs
using DAL.Models;
using Dashboard_Ecommerce.Dtos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace Dashboard_Ecommerce.Controllers
{
    public class CompanyController : Controller
    {
        private  MoDbContext _db ;
        private readonly IToastNotification _toastNotification;

        public CompanyController(MoDbContext db,IToastNotification toastNotification)
        {
            _db = db;
            _toastNotification = toastNotification;
        }


        public async Task<IActionResult> Index()
        {
            MsCompany CompanyWord = await _db.MsCompanies.FirstOrDefaultAsync();
            return View(CompanyWord);
        }

        public async Task<IActionResult> Edit (int CompanyId)
        {
            if(CompanyId == 0)  return BadRequest("there are no data with this id"); 

            MsCompany GetCompanyWordData = await _db.MsCompanies.FirstOrDefaultAsync(c=>c.CompanyId == CompanyId);

            if (GetCompanyWordData == null) return NotFound("i can not found the data");

            MsCompanyDto dto = new MsCompanyDto
            {
              CompanyId = GetCompanyWordData.CompanyId,
              RemarksA = GetCompanyWordData.RemarksA,
              RemarksE = GetCompanyWordData.RemarksE,
            };

            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(MsCompanyDto dto)
        {
            if(!ModelState.IsValid) return View(dto) ;

            if (dto.CompanyId == null) return BadRequest("there are no data with this id");

            MsCompany GetCompanyWordData = await _db.MsCompanies.FirstOrDefaultAsync(c => c.CompanyId == dto.CompanyId);

            if (GetCompanyWordData == null) return NotFound("i can not found the data");

            GetCompanyWordData.RemarksA = dto.RemarksA;
            GetCompanyWordData.RemarksE = dto.RemarksE;

             _db.SaveChanges();

            _toastNotification.AddSuccessToastMessage("data Updated Successfully");
            return RedirectToAction("index");
        }
    }
}

Dashboard-Ecommerce/Controllers/MembersController.cs
using DAL.Identity;
using infrastrucure.Identity;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using X.PagedList;

namespace Dashboard_Ecommerce.Controllers
{
    public class MembersController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public MembersController(UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(int pageIndex = 1, int pageSize = 50)
        {
            var users = await _userManager.Users.Where(s=>s.DeletedAt == null).ToPagedListAsync(pageIndex, pageSize);

            return View(users);
        }

        public async Task<IActionResult> search(int pageIndex = 1, int pageSize = 50,string phone = "")
        {
            if(phone != string.Empty)
            {
                ViewBag.term = phone;
            }
            var users = await _userManager.Users.Where(s => s.DeletedAt == null && s.PhoneNumber == phone).ToPagedListAsync(pageIndex, pageSize);

            return View("index", users);
        }

        public async Task<IActionResult> delete(string id)
        {
            if(id == null) return BadRequest("empty id");

            AppUser user = await _userManager.Users.FirstOrDefaultAsync(s=>s.Id == id);

            if (user == null) return NotFound("user not found");

            user.DeletedAt = DateTime.Now;

            var result = await _userManager.DeleteAsync(user);

            if (result.Succeeded)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                // يمكنك التعامل مع الأخطاء هنا إذا لزم الأمر
                return RedirectToAction(nameof(Index));
            }


        }


    }
}

Dashboard-Ecommerce/Views/Shared/_Layout.cshtml
@inject SignInManager<DashBoardUser> UserManager;


<!DOCTYPE html>


<html>

<head>
    <meta charset="utf-8">
    <title>E-Commerce DashBoard</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/content/images/Beshai Logo_Final Ceramic Final-01.png" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600;700&display=swap" rel="stylesheet">
@*    @RenderSection("Styles",false);
*@
    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="~/content/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
    <!-- Libraries Stylesheet -->
    <link href="~/content/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/content/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/content/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/content/css/style.css" rel="stylesheet">
    <link href="~/content/lib/animate.css/animate.min.css" rel="stylesheet" />
    
</head>

<body>
    <div class="container-xxl position-relative bg-white d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">

            <nav class="navbar bg-light navbar-light">
                <a asp-action="Index" asp-controller="Home" class="navbar-brand mx-4 mb-3">
                   @* <h3 class="text-primary" style="font-size:larger">Eldolia DashBoard</h3>*@
                    <img src="~/content/images/Beshai Logo_Final Ceramic Final-01.png" style="width:150px"/>

                </a>
             @*   <div class="d-flex align-items-center ms-4 mb-4">
                   
         

                    <div class="position-relative">
                        <img class="rounded-circle" src="~/content/images/StaticImages/admin.png" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>

                    </div>

              
                    <div class="ms-3">
                        <a href="" class="mb-0" style="text-decoration:none;font-weight: 700;line-height: 1.2;color: #191C24;">Admin</a>
                    </div>
                </div>*@

                <div class="navbar-nav w-100">
                    <a asp-action="Index" asp-controller="Home" class="nav-item nav-link"><i class="fa fa-home me-2" aria-hidden="true"></i>Home Page</a>
@*                     <a asp-action="Index" asp-controller="Company" class="nav-item nav-link"><i class="fa fa-home me-2" aria-hidden="true"></i>Company Word</a>
 *@                    <!-- Example single danger button -->
                    <!-- Example split danger button -->
                    

                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="cursor:pointer"><i class="bi bi-tags-fill me-2"></i>Our Brands</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a asp-action="Index" asp-controller="Brand" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>View All Brands</a>
                            <a asp-controller="Brand" asp-action="Create" class="nav-item nav-link"><i class="bi bi-plus-circle-fill me-2"></i>Add New Brand</a>

                        </div>
                    </div>

                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="cursor:pointer"><i class="fa fa-bookmark me-2" aria-hidden="true"></i>Our Types</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a asp-action="Index" asp-controller="Category" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>View All Category</a>
                            <a asp-controller="Category" asp-action="Create" class="nav-item nav-link"><i class="bi bi-plus-circle-fill me-2"></i>Add New Category</a>

                        </div>
                    </div>

                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="cursor:pointer"><i class="bi bi-diagram-3-fill me-2" aria-hidden="true"></i>Our Products</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a asp-action="Index" asp-controller="Products" class="nav-item nav-link"><i class="fa fa-chart-bar me-2"></i>View All Product</a>
                            <a asp-controller="Products" asp-action="Create" class="nav-item nav-link"><i class="bi bi-plus-circle-fill me-2"></i>Add Product</a>
                        @*    <a asp-controller="Products" asp-action="GetProductsWithOffer" class="nav-item nav-link"><i class="fa fa-bell me-2"></i> offers</a>
                            <a asp-controller="Products" asp-action="GetProductsWithOutOffer" class="nav-item nav-link"><i class="fa fa-bell-slash me-2"></i>ًًWith Out offers</a>
                            <a asp-controller="Products" asp-action="GetFinishedProducts" class="nav-item nav-link"><i class="fa fa-eye me-2"></i>Not available</a>*@

                        </div>
                    </div>


                    <a asp-action="Index" asp-controller="UsersOrder" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i> User Orders</a>
                    <a asp-action="Index" asp-controller="Complaints" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i> User Complaints</a>
                    <a asp-action="Index" asp-controller="unvalibleProduct" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i> Unavaliable</a>
                    <a asp-action="Index" asp-controller="Discount" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i> Discounts </a>
                    <a asp-action="Index" asp-controller="SendOffers" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i> Send offers</a>
                    <a asp-action="Index" asp-controller="Members" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i> Our Members</a>
                    <a asp-action="Index" asp-controller="OurCustomer" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i> Our Customer</a>
                    <a asp-action="GetAllAdmin" asp-controller="User" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i> Our Admins</a>
                    <a asp-action="CreateUser" asp-controller="User" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i>Create User </a>
                    <a asp-action="SignUp" asp-controller="User" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i> Create Admin</a>

@*                    <a asp-action="SignIn" asp-controller="User" class="nav-item nav-link"><i class="fa fa-user-circle" aria-hidden="true"></i> SignIn</a>
*@
                    
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-light navbar-light sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-hashtag"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
               @* <form class="d-flex FormHidden" asp-controller="Products" asp-action="Search">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" name="term" style="margin-right:5px;margin-left:10px;" />
                    <button type="submit" class="btn btn-outline-success btn-sm">Search</button>
                    <a asp-controller="Products" asp-action="index" class="btn btn-secondary btn-sm" style="font-size: initial;margin-left:5px;">Reset</a>
                </form>*@
                <div class="navbar-nav align-items-center ms-auto">
                 
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="~/content/images/StaticImages/admin.png" alt="" style="width: 40px; height: 40px;">
                            @if (UserManager.IsSignedIn(User) == true)
                            {
                                <span class="d-none d-lg-inline-flex">@User.Identity.Name</span>
                            }else
                            {
                            <span class="d-none d-lg-inline-flex">Admin</span>

                            }
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-light border-0 rounded-0 rounded-bottom m-0">
                            <a class="dropdown-item" asp-action="SignOut" asp-controller="User">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
           
         
            <!-- Recent Sales Start -->
            <div class="container-fluid pt-4 px-4">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <!-- Recent Sales End -->
          
            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-light rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                           <a href="#">E-Commerce DashBoard</a>
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="">Soft Go Solutions</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
@*     <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
 *@    <script src="~/content/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)


@*    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
*@    <script src="~/content/lib/chart/chart.min.js"></script>
    <script src="~/content/lib/easing/easing.min.js"></script>
    <script src="~/content/lib/waypoints/waypoints.min.js"></script>
    <script src="~/content/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/content/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/content/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/content/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <
    <script src="~/content/lib/bootbox.js/bootbox.min.js"></script>
    <script src="~/content/js/main.js"></script>
    <script src="~/content/lib/bootstrap/dist/js/bootstrap.js"></script>

    @await Component.InvokeAsync("NToastNotify")

</body>

</html>