Dashboard-Ecommerce/Controllers/DiscountController.cs
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Dashboard_Ecommerce.Controllers
{
    public class DiscountController : Controller
    {
        private readonly MoDbContext _db;
        public DiscountController(MoDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult>  Index()
        {
            MsSalesItemsOffer DiscountDescription = await _db.MsSalesItemsOffers
                .Select(item => new MsSalesItemsOffer { PromoOfferId = item.PromoOfferId , Name1 = item.Name1, Name2 = item.Name2 })
                .FirstOrDefaultAsync();


            return View(DiscountDescription);
        }


        public async Task<IActionResult> Edit(int PromoOfferId)
        {
            MsSalesItemsOffer getRecord = await _db.MsSalesItemsOffers.FindAsync(PromoOfferId);

            return View(getRecord);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(MsSalesItemsOffer offer)
        {
            if (offer == null) return BadRequest("oblect is empty");

            MsSalesItemsOffer getRecord = await _db.MsSalesItemsOffers.FindAsync(offer.PromoOfferId);

            if(getRecord == null) return NotFound("i do not found any record with this id" );


            getRecord.Name1 = offer.Name1;
            getRecord.Name2 = offer.Name2;

            _db.SaveChanges();

            return RedirectToAction("index");
             
            
        }
    }
}

Dashboard-Ecommerce/Views/Discount/Edit.cshtml
@model MsSalesItemsOffer
@{
    ViewData["Title"] = "Discount Form";
}

<h2>Edit Discount</h2>


<hr />

<section class="row">
    <div class="col-md-5">
        <form method="POST" asp-action="Edit" >
            <input type="hidden" asp-for="PromoOfferId" />
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label text-muted">ِDiscount Arabic</label>
                <input type="text" class="form-control" asp-for="Name1" maxlength="50">
                <span asp-validation-for="Name1" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label text-muted">ِDiscount English</label>
                <input type="text" class="form-control" asp-for="Name2" maxlength="50">
                <span asp-validation-for="Name2" class="text-danger"></span>
            </div>

    

            <button type="submit" class="btn btn-primary"><i class="bi bi-check"></i> Save</button>
            <a asp-controller="Discount" asp-action="Index" class="btn btn-outline-secondary"><i class="bi bi-x"></i> Cancel</a>
        </form>
    </div>
    </section>

Dashboard-Ecommerce/Views/Discount/Index.cshtml
@model MsSalesItemsOffer




<div class="mt-4">
    @if (Model == null)
    {
        <div class="alert alert-warning" role="alert">
            لا توجد عروض
        </div>
    }
    else
    {
        <div class="table-responsive">
            <table class="table text-start align-middle table-bordered table-hover mb-0">
                <thead>
                    <tr class="text-dark">
                        <th scope="col">وصف العرض بالعربى</th>
                        <th scope="col">وصف العرض بالانجليزى</th>
                        <th scope="col">تعديل</th>
                     
                    </tr>
                </thead>
                <tbody>
                        <tr class="p">
                        <td>@Model.Name1</td>
                        <td>@Model.Name2</td>
                        <td><a class="btn btn-sm btn-primary" asp-action="Edit" asp-route-PromoOfferId="@Model.PromoOfferId">Edit</a></td>
                        </tr>
                </tbody>
            </table>
        </div>
    }
</div>